blueprint:
  name: Paralelo Virtual por Grupo
  description: >
    Sincroniza um grupo com switches controladores de forma confiável.
    Versão otimizada para evitar loops e falhas.
  domain: automation
  source_url: https://github.com/lucianotuma/homeassistant/blueprints/paralelo-grupo.yaml
  input:
    controladores:
      name: Canais/entidades controladoras
      description: Selecione os switches que controlam o grupo
      selector:
        entity:
          multiple: true
          filter:
            - domain: light
            - domain: switch
    grupo_alvo:
      name: Grupo alvo
      description: Selecione o grupo que deve ser controlado
      selector:
        entity:
          multiple: false
          filter:
            - domain: light
            - domain: group

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input controladores
    to:
      - "on" 
      - "off"
    not_from:
      - "unavailable"
      - "unknown"

variables:
  grupo: !input grupo_alvo
  novo_estado: "{{ trigger.to_state.state }}"

condition:
  # Só executa se o grupo não está já no estado desejado
  - condition: template
    value_template: "{{ states(grupo) != novo_estado }}"

action:
  # Pequeno delay para evitar conflitos na rede Zigbee
  - delay:
      milliseconds: 50
      
  # Envia o comando usando service (não action!)
  - service: "homeassistant.turn_{{ novo_estado }}"
    data: {}
    target:
      entity_id: "{{ grupo }}"
