blueprint:
  name: Paralelo Virtual por Grupo (Força Sempre)
  description: >
    Sincroniza um grupo com switches controladores.
    Sempre envia o comando, independente do estado atual.
  domain: automation
  input:
    controladores:
      name: Canais/entidades controladoras
      selector:
        entity:
          multiple: true
          filter:
            - domain: light
            - domain: switch
    grupo_alvo:
      name: Grupo alvo (preferir ZHA Group: light.zha_group_*)
      selector:
        entity:
          multiple: false
          filter:
            - domain: light
            - domain: group
    atraso_ms:
      name: Atraso (ms) opcional para debounce
      default: 0
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: ms
          mode: box

mode: queued
max: 10

trigger:
  - platform: state
    entity_id: !input controladores
    to: 
      - "on"
      - "off"

variables:
  grupo: !input grupo_alvo
  atraso: !input atraso_ms
  to_state: "{{ 'on' if trigger.to_state.state == 'on' else 'off' }}"

action:
  - choose: []
    default:
      - delay:
          milliseconds: "{{ atraso }}"
      - service: "homeassistant.turn_{{ to_state }}"
        target:
          entity_id: "{{ grupo }}"
