blueprint:
  name: Paralelo Virtual por Grupo (Força Sempre)
  description: >
    Sincroniza um grupo com switches controladores.
    Sempre envia o comando, independente do estado atual.
  domain: automation
  input:
    controladores:
      name: Canais/entidades controladoras
      description: Selecione os switches que controlam o grupo
      selector:
        entity:
          multiple: true
          filter:
            - domain: light
            - domain: switch
    grupo_alvo:
      name: Grupo alvo
      description: Selecione o grupo que deve ser controlado
      selector:
        entity:
          multiple: false
          filter:
            - domain: light
            - domain: group

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input controladores
    to:
      - "on" 
      - "off"

variables:
  grupo: !input grupo_alvo

action:
  - service: "homeassistant.turn_{{ trigger.to_state.state }}"
    data: {}
    target:
      entity_id: "{{ grupo }}"
